const TELAS = {
  TELA_ABERTURA: "TELA_ABERTURA",
  TELA_LOGIN: "TELA_LOGIN",
  TELA_CADASTRO_USUARIO: "TELA_CADASTRO_USUARIO",
  TELA_PRINCIPAL: "TELA_PRINCIPAL",
  TELA_CADASTRO_PRODUTO: "TELA_CADASTRO_PRODUTO",
};

export default TELAS;
