const TELAS = {
  //GRUPO 1
  TELA_BOAS_VINDAS: "TELA_BOAS_VINDAS",
  TELA_LOGIN: "TELA_LOGIN",
  TELA_CADASTRO_USUARIO: "TELA_CADASTRO_USUARIO",

  //GRUPO 2 - DENTRO DO APP
  TELA_PRINCIPAL: "TELA_PRINCIPAL",

  TELA_LISTA_ANUNCIO: "TELA_LISTA_ANUNCIO",

  TELA_ANUNCIO_DETALHADO: "TELA_ANUNCIO_DETALHADO",
  TELA_ANUNCIO_DETALHADO_PRODUTO: "TELA_ANUNCIO_DETALHADO_PRODUTO",
  TELA_ANUNCIO_DETALHADO_SERVICO: "TELA_ANUNCIO_DETALHADO_SERVICO",

  TELA_PERFIL_USUARIO: "TELA_PERFIL_USUARIO",

  TELA_CADASTRO_PRODUTO: "TELA_CADASTRO_PRODUTO",
  TELA_EDITAR_CADASTRO_PRODUTO: "TELA_EDITAR_CADASTRO_PRODUTO",

  TELA_CADASTRO_SERVICO: "TELA_CADASTRO_SERVICO",
  TELA_EDITAR_CADASTRO_SERVICO: "TELA_EDITAR_CADASTRO_SERVICO",

  TELA_MEUS_ANUNCIOS: "TELA_MEUS_ANUNCIOS",
};

export default TELAS;
